export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  ALERT: 'ALERT',
  SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE'
}
export const userConstants = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE'

}

export const categoryConstants ={
  CATEGORY_REQURES : 'CATEGORY_REQUEST',
  CATEGORY_SUCCESS : 'CATEGORY_SUCCESS',
  CATEGORY_FAILURE : 'CATEGORY_FAILURE',
  ADD_CATEGORY_REQUEST :'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE : 'ADD_CATEGORY_FAILURE'

}
