export const authConstants = {
  LOGIN_REQUEST : 'LOGIN_REQUEST',
  LOGIN_FAILURE : 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  ALERT:'ALERT',
  SIGNOUT_REQUEST:'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE : 'SIGNOUT_FAILURE'
}